### ISSUE TITLE
[QST] failure to compile due to `identifier "__int128_t" is undefined`

### ISSUE THREAD

**Issue by jsonstro** [rapidsai/cudf#10351]
Hi cuDF folks,

I'm a HPC sysadmin and I've been struggling to get cuDF successfully built on a medium size Centos 7 cluster. I'm not using the conda environment but attempting to compile from source so that I can have the software loaded via our module system. I'm using the GCC 9 devtoolset, python 3.8.6, cmake 3.22, cuda 11.2 suite, cuDNN 8.1.0 and the 460.32 NVIDIA drivers. I've successfully built and verified arrow/pyarrow 7, rmm 22.02 and cuSIGNAL 21.12 are working in my python environment. I have installed all the dependencies as called for in the CONDA environment list for version 22/21 of the cuDF build. 

Before I get into my issues with the builds of both version 22 and 21 I was curious if its possible to build either of those versions of cuDF using arrow 7 since I already have it installed and working in my python environment (and built rmm and cuSIGNAL against it). I have not been able to figure out a way to get the cuDF build process to find and link to that version and the build seems to want arrow 6 for v22 and arrow 5 for v21. Is that a possibility to use my preexisting version 7 of arrow/pyarrow for v22 or v21 of cuDF?

As for the my issues with the two cuDF builds that fail, the details are as follows. When I try to build version 22 using our enviroment I encounter an issue related to the __int_128_t not existing in our system. I tried setting Set ARROW_USE_NATIVE_INT128:INTERNAL=0 but it still runs into the issue. The error is as follows:

Error processing source file binaryop/jit/kernel.cu
Compilation failed: NVRTC_ERROR_COMPILATION
Compiler options: "-std=c++17 -D__CUDACC_RTC__ -default-device"
cudf/fixed_point/fixed_point.hpp(28): error: identifier "__int128_t" is undefined

1 error detected in the compilation of "binaryop/jit/kernel.cu".

make[2]: *** [CMakeFiles/jitify_preprocess_run.dir/build.make:78: include/jit_preprocessed_files/binaryop/jit/kernel.cu.jit.hpp] Error 1
make[1]: *** [CMakeFiles/Makefile2:777: CMakeFiles/jitify_preprocess_run.dir/all] Error 2

This has kept me from being able to build version 22 so I decided to try version 21.

Any ideas about how to fix this?

thanks,
Josh

**Comment by jrhemstad** [comment]
Hey @jsonstro what's happening is it's attempting to compile a kernel with NVRTC that doesn't support `__int128_t` without an additional `--device-int128` flag. I was under the impression that this had been fixed in https://github.com/rapidsai/cudf/pull/9794 by removing this code all together. So you're not doing anything wrong.

@robertmaynard I thought we removed the jit binops in https://github.com/rapidsai/cudf/pull/9794. Why is this still coming up in 21.12? How was our CI able to pass if @jsonstro is hitting this?

**Comment by robertmaynard** [comment]
> Hey @jsonstro what's happening is it's attempting to compile a kernel with NVRTC that doesn't support `__int128_t` without an additional `--device-int128` flag. I was under the impression that this had been fixed in #9794 by removing this code all together. So you're not doing anything wrong.
> 
> @robertmaynard I thought we removed the jit binops in #9794. Why is this still coming up in 21.12? How was our CI able to pass if @jsonstro is hitting this?

We still use jitify to build a collection of files. The difference is now we only do this during the larger cudf compilation phase, instead of doing it at user runtime.

I believe the root cause is using the `cuda 11.2` compilers when building cudf, as for 21.12 we require 11.5+

**Comment by jrhemstad** [comment]
But the error is specifically an NVRTC error:

```
Error processing source file binaryop/jit/kernel.cu
Compilation failed: NVRTC_ERROR_COMPILATION
```

Are we passing `--device-int128` to the Jitify flags?

**Comment by robertmaynard** [comment]
> Are we passing `--device-int128` to the Jitify flags?

Nope, we don't pass that flag nor does jitify add it.  Looking into it more the first usage of `__int128_t` in cudf/fixed_point/fixed_point.hpp is for host code. It makes me think that on this machine the system gcc headers are not providing the `__int128_t` type at all.

**Comment by jsonstro** [comment]
Ok, thanks for the info y'all. I can try to build v22 with cuda-11.5 and see if its any better. As for if the __int128_t  headers are there at all, how do I check that? Is that something that needs to be installed via the devtoolset-9 packages?

I've been able to get version 21.12.0a to build with my environment as it is, but it has been quite frustrating. I'm still not sure how exactly to get the cuDF build process to recognize and use my existing arrow/pyarrow installation. I've tried setting ARROW_HOME and ARROW_ROOT as well as passing in -DArrow_DIR to cmake and it still doesn't "find" the existing installation the way it does if I reuse the internal build. When I do include the external arrow I get a strange and frustrating cmake error that one of the arrow build targets -- I believe its arrow_static -- are already defined. Is there a proper way to pass in the prexisting arrow v5.0.0 so that it doesn't have to rebuild it?

Thanks again

**Comment by robertmaynard** [comment]
> Ok, thanks for the info y'all. I can try to build v22 with cuda-11.5 and see if its any better. As for if the __int128_t headers are there at all, how do I check that? Is that something that needs to be installed via the devtoolset-9 packages?

You can try to compile a simple project and see if int128 is supported. Something like this should work when compiled via `<g++-9> -c test.cpp`:

```cpp
int main() {
  const __int128_t value = 0;
  return value;
}
```

> I'm still not sure how exactly to get the cuDF build process to recognize and use my existing arrow/pyarrow installation.

My recommendation is to specify the root of the installed Arrow directory to CMake via `-DCMAKE_PREFIX_PATH` that will work as long as the Arrow version is the same as the one cudf is looking for. If the major values are different it isn't considered a match and will be ignored.

> When I do include the external arrow I get a strange and frustrating cmake error that one of the arrow build targets -- I believe its arrow_static

Can you post the error you are getting? If I can reproduce it I can get a fix in for future cudf releases so that we don't have this issue going forward.

**Comment by jsonstro** [comment]
Thanks Robert, I really appreciate your help. I tested compiling the c++ code that you sent and it did work. 

# g++ -c !$
g++ -c ~jsonstro/int128_test.cpp

# cat int128_test.o 
ELF> @@

��int128_test.cppmain .symtab.strtab.shstrtab.text.data.bss.comment.note.GNU-stack.rela.eh_frame@![[,0[-5�J�E�� ��T

Do I supply the -DCMAKE_PREFIX_PATH at the top level configure step for cuDF? Or do I need to slip that into the CMakeCache.txt within the arrow_src folder within the project? 

As for the arrow include here is the exact error I get when I specify an ARROW_HOME or Arrow_DIR within the build process for v21

CMake Error at build/_deps/arrow-src/cpp/cmake_modules/BuildUtils.cmake:327 (add_library):
  add_library cannot create target "arrow_shared" because an imported target
  with the same name already exists.
Call Stack (most recent call first):
  build/_deps/arrow-src/cpp/src/arrow/CMakeLists.txt:511 (add_arrow_lib)

CMake Error at build/_deps/arrow-src/cpp/cmake_modules/BuildUtils.cmake:371 (target_link_libraries):
  Cannot specify link libraries for target "arrow_shared" which is not built
  by this project.
Call Stack (most recent call first):
  build/_deps/arrow-src/cpp/src/arrow/CMakeLists.txt:511 (add_arrow_lib)

Let me know if you need anything else.
Josh

**Comment by robertmaynard** [comment]
Interesting I am stumped on how to reproduce this failure when trying with cuda 11.5.

using the following docker containr:

```
FROM nvidia/cuda:11.5.0-devel-centos7

RUN yum upgrade -y && yum install -y wget centos-release-scl
RUN yum install -y devtoolset-9 git zlib-devel

RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.sh
RUN chmod +x https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.sh
RUN ./cmake-3.22.2-linux-x86_64.sh --skip-license --prefix=/usr/local

RUN echo "source /opt/rh/devtoolset-9/enable" >> /etc/bashrc
SHELL ["/bin/bash", "--login", "-c"]
```

Using that as the base building ground for cudf I get zero build failures. So I am confused on why for your builds you aren't getting the correct importation of `__int128_t` given that the gcc sample behavior.

**Comment by jsonstro** [comment]
Hi Robert,

I think the issue is that I am building against CUDA 11.2. I still don't understand why its able to find the headers with the c++ code but not in the build, but maybe that is fine. I was able to get a build of v21 complete and working so we can close this out.

thanks again,
Josh

**Comment by chenrui17** [comment]
@robertmaynard  
Hi Robert,
I met the same problem 
![image](https://user-images.githubusercontent.com/33319780/213139061-d0f9c44a-71e9-424a-8af6-49620019068c.png)

Though my cuda version is 11.4, but use your test code I can compile successfully
```
int main() {
  const __int128_t value = 0;
  return value;
}

[chenrui17@yq01-sys-hic-v100-box-a62-0038 ~/cudf/cpp/build]$ cat test.o
ELF>@@

VH��H�E�H�E��]�GCC: (GNU) 10.1.0zR�A�C
��
test.cppmain .symtab.strtab.shstrtab.text.data.bss.comment.note.GNU-stack.rela.eh_frame@![[,0[5nJpE��	��T

```
so could i build libcudf based my environment? how to solved this problem except update my cuda version, if no way, Can I remove this part in the compilation process, because currently my application only needs IO module, please give me some advice , Thanks a lot.

**Environment details**
<details><summary>Click here to see environment details</summary><pre>

     **git***
     commit aa58765f44d0c85e081f589edf45d58460fcf098 (HEAD -> branch-22.08, origin/branch-22.08)
     Author: GALI PREM SAGAR <sagarprem75@gmail.com>
     Date:   Thu Sep 29 13:12:45 2022 -0500

     pin numpy version (#11824)

     ## Description
     Because of the issue discovered here: https://github.com/rapidsai/cudf/pull/11816, we would like to pin the max version of `numpy` to `<1.23` thus averting the same error in `22.08`.

     ## Checklist
     - [x] I am familiar with the [Contributing Guidelines](https://github.com/rapidsai/cudf/blob/HEAD/CONTRIBUTING.md).
     - [x] New or existing tests cover these changes.
     - [x] The documentation is up to date with these changes.

     Authors:
     - GALI PREM SAGAR (https://github.com/galipremsagar)

     Approvers:
     - Ray Douglass (https://github.com/raydouglass)
     **git submodules***

     ***OS Information***
     CentOS release 6.3 (Final)
     CentOS release 6.3 (Final)
     CentOS release 6.3 (Final)
     Linux yq01-sys-hic-v100-box-a62-0038.yq01.baidu.com 4.14.0_1-0-0-44 #1 SMP Tue Sep 14 17:12:22 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

     ***GPU Information***
     Wed Jan 18 17:51:17 2023
     +-----------------------------------------------------------------------------+
     | NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
     |-------------------------------+----------------------+----------------------+
     | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
     | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
     |                               |                      |               MIG M. |
     |===============================+======================+======================|
     |   0  Tesla V100-SXM2...  On   | 00000000:29:00.0 Off |                    0 |
     | N/A   33C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   1  Tesla V100-SXM2...  On   | 00000000:2A:00.0 Off |                    0 |
     | N/A   33C    P0    44W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   2  Tesla V100-SXM2...  On   | 00000000:2B:00.0 Off |                    0 |
     | N/A   38C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   3  Tesla V100-SXM2...  On   | 00000000:2C:00.0 Off |                    0 |
     | N/A   38C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   4  Tesla V100-SXM2...  On   | 00000000:5D:00.0 Off |                    0 |
     | N/A   33C    P0    43W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   5  Tesla V100-SXM2...  On   | 00000000:5E:00.0 Off |                    0 |
     | N/A   34C    P0    41W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   6  Tesla V100-SXM2...  On   | 00000000:5F:00.0 Off |                    0 |
     | N/A   36C    P0    45W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+
     |   7  Tesla V100-SXM2...  On   | 00000000:60:00.0 Off |                    0 |
     | N/A   38C    P0    45W / 300W |      0MiB / 32510MiB |      0%      Default |
     |                               |                      |                  N/A |
     +-------------------------------+----------------------+----------------------+

     +-----------------------------------------------------------------------------+
     | Processes:                                                                  |
     |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
     |        ID   ID                                                   Usage      |
     |=============================================================================|
     |  No running processes found                                                 |
     +-----------------------------------------------------------------------------+

     ***CPU***
     Architecture:          x86_64
     CPU op-mode(s):        32-bit, 64-bit
     Byte Order:            Little Endian
     CPU(s):                160
     On-line CPU(s) list:   0-159
     Thread(s) per core:    2
     Core(s) per socket:    20
     CPU socket(s):         4
     NUMA node(s):          4
     Vendor ID:             GenuineIntel
     CPU family:            6
     Model:                 85
     Stepping:              4
     CPU MHz:               3100.138
     BogoMIPS:              4810.65
     Virtualization:        VT-x
     L1d cache:             32K
     L1i cache:             32K
     L2 cache:              1024K
     L3 cache:              28160K
     NUMA node0 CPU(s):     0-19,80-99
     NUMA node1 CPU(s):     20-39,100-119
     NUMA node2 CPU(s):     40-59,120-139
     NUMA node3 CPU(s):     60-79,140-159

     ***CMake***
     /home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin/cmake
     cmake version 3.25.1

     CMake suite maintained and supported by Kitware (kitware.com/cmake).

     ***g++***
     /home/opt/compiler/gcc-10-r5/bin/g++
     g++ (GCC) 10.1.0
     Copyright (C) 2020 Free Software Foundation, Inc.
     This is free software; see the source for copying conditions.  There is NO
     warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


     ***nvcc***
     /usr/local/cuda/bin/nvcc
     nvcc: NVIDIA (R) Cuda compiler driver
     Copyright (c) 2005-2021 NVIDIA Corporation
     Built on Wed_Jul_14_19:41:19_PDT_2021
     Cuda compilation tools, release 11.4, V11.4.100
     Build cuda_11.4.r11.4/compiler.30188945_0

     ***Python***
     /home/users/chenrui17/.jumbo/bin/python
     Python 2.7.3

     ***Environment Variables***
     PATH                            : /home/users/chenrui17/.BCloud/bin:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-10-r5/bin/:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-12/bin/:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/opt/compiler/gcc-10-r5/bin/:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-8.2/gcc-8.2/bin:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/opt/compiler/gcc-10-r5/bin/:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-8.2/gcc-8.2/bin:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/opt/compiler/gcc-10-r5/bin/:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-8.2/gcc-8.2/bin:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/users/chenrui17/tools/cmake-3.25.1-linux-x86_64/bin:/home/opt/compiler/gcc-8.2/gcc-8.2/bin:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/home/users/chenrui17/.BCloud/bin:/home/opt/compiler/gcc-8.2/gcc-8.2/bin:/home/users/chenrui17/hadoop-client/hadoop/bin:/home/users/chenrui17/.jumbo/bin/core_perl:/home/users/chenrui17/.jumbo/bin:/usr/local/cuda/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/bin:/home/opt/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin:/home/users/chenrui17/bin
     LD_LIBRARY_PATH                 : /usr/local/cuda/lib64
     NUMBAPRO_NVVM                   :
     NUMBAPRO_LIBDEVICE              :
     CONDA_PREFIX                    :
     PYTHON_PATH                     :

     conda not found
     ***pip packages***
     /home/users/chenrui17/.jumbo/bin/pip
     Package             Version
     ------------------- -------
     numpy               1.19.5
     paddlecloudplatform 3.0.11
     pip                 9.0.1
     setuptools          28.8.0
     six                 1.16.0
You are using pip version 9.0.1, however version 22.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

</pre></details>

**Comment by robertmaynard** [comment]
Unforunately you will need to update your CUDA version to at least 11.5 to compile libcudf. Your tests shows that you can use `__int128_t` in CPU host code which is insufficient for libcudf which requires CUDA device side ( GPU ) `__int128_t` support which requires CUDA 11.5+.

As `__int128_t` is part of the fundamental types that libcudf supports you can't choose to remove it.
