### ISSUE TITLE
[FEA] cuDF column names stored with different data type compared to Pandas

### ISSUE THREAD

**Issue by miguelangel** [rapidsai/cudf#1593]
**Is your feature request related to a problem? Please describe.**
Hi,

It looks like cuDF always stores column names as strings. 

That behaviour is different from Pandas.

Please, find below a picture where it can be easily seen the differences:

![image](https://user-images.githubusercontent.com/26169771/57097552-47a2b900-6d18-11e9-823b-8f7a5d757fcf.png)

**Describe the solution you'd like**
Same behaviour as Pandas.

**Describe alternatives you've considered**
None yet.

**Additional context**

**Comment by j-ieong** [comment]
Actually, `cudf.read_csv("temp.csv", names=[3, 4])` should work now. `range` should also work.
See [test_csv_reader_column_names](https://github.com/rapidsai/cudf/blob/7fc958c430801efbbf25c71179453f27af2827ca/python/cudf/tests/test_csvreader.py#L913) in the pytests for all the working parameters.

The problem is that mixing of different types or using non-Int and non-String types such as `float` do not work. Examples not currently working (either due to cudf Dataframe missing support, or CSV reader not handling):
```python
cudf.read_csv("temp.csv", names=[3.14, 0.01])
```
```python
cudf.read_csv("temp.csv", names=[4, 'four'])
```

**Comment by miguelangel** [comment]
Hi @j-ieong,

What you state is completely right, but there is also a difference in usage. 

In my example above, I am using integer values only. 

In cells #2 and #3 of my example, it can be noticed that cudf produces an error message when trying to access the columns with integer column names.

I would say that this is happening because the columns are always converted to string datatype. 

Hope it helps.

Regards,
Miguel

**Comment by j-ieong** [comment]
@miguelangel,
Do you mean that this still does not work?
```python
gdf = cudf.read_csv("sample.csv", names=[3,4])
print(gdf[3].head())
```
The fix for it was merged in yesterday, hence why the Issue was closed...?

**Comment by miguelangel** [comment]
Hi @j-ieong,

Let try with the latest nightly build. I will be back in a few minutes...

**Comment by miguelangel** [comment]
Hi @j-ieong,

I will test it when the new nightly build is available (the current one is two days old, and still failing).

I will write back soon.

Regards,
Miguel

**Comment by miguelangel** [comment]
> @miguelangel,
> Do you mean that this still does not work?
> 
> ```python
> gdf = cudf.read_csv("sample.csv", names=[3, 4])
> print(gdf[3].head())
> ```
> 
> The fix for it was merged in yesterday... it's in the latest code if you pull and build it...
Hi all,

I have just tested with the latest nightly-build, and that error is not present anymore.

**Comment by kkraus14** [comment]
Thanks @miguelangel, closing the issue.
