### ISSUE TITLE
pygdf.DataFrame.merge() output column order differs from pd.DataFrame.merge()

### ISSUE THREAD

**Issue by harrism** [rapidsai/cudf#251]
When performing a merge, the output column order is different between pygdf and Pandas. Minimal reproducer:

```
gdf1 = pygdf.DataFrame()
gdf2 = pygdf.DataFrame()
gdf1['id'] = [10, 11]
gdf1['timestamp'] = [1,2]
gdf1['a'] = [3, 4]

gdf2['id'] = [4,5]
gdf2['a'] = [7, 8]

gdf = gdf1.merge(gdf2, how='left', on=['id', 'a'], type='hash')
print(gdf)

df1 = pd.DataFrame()
df2 = pd.DataFrame()
df1['id'] = [10, 11]
df1['timestamp'] = [1,2]
df1['a'] = [3, 4]

df2['id'] = [4,5]
df2['a'] = [7, 8]

df = df1.merge(df2, how='left', on=['id', 'a'])
print(df)
```

Output:

```
    id    a timestamp
0   10    3         1
1   11    4         2
   id  timestamp  a
0  10          1  3
1  11          2  4
```

**Comment by mt-jones** [comment]
Is this a problem provided the column header is still correct?

**Comment by harrism** [comment]
It is a minor problem when comparing results between pygdf and pandas for correctness. It requires you to reorder the columns in one data frame in order to compare the two. E.g. comparing like this returns False: `print(df.equals(gdf.to_pandas()))`. To get a True comparison you have to do this, which is non-obvious: `print(df.equals(gdf.to_pandas()[df.columns]))`. One might think to do this:
`print(df.equals(gdf[df.columns].to_pandas()))`, but that gives an error, as does this: `print(df[gdf.columns].equals(gdf.to_pandas()))`.

I'm not a pandas expert -- maybe the different ordering could lead to other issues as well.  I understand that rows are out of order in the parallel version, due to the lack of guarantees on parallel ordering. But I don't see why columns should exhibit that effect.

I would not say this is high priority, but I wanted to log the issue so that if it causes others problems, at least something will come up when they search for it.

**Comment by kkraus14** [comment]
This will effect the output of other operations such as `.as_matrix()` or `.as_gpu_matrix()` as well

**Comment by dantegd** [comment]
Is seems to me that things like `print(df.equals(gdf[df.columns].to_pandas()))` not working well are  bugs that need to be tackled. I'm not entirely convinced that we should follow the same order (or at least spend too much effort pursuing it), as long as we are consistent and headers are correct (and bugs are fixed of course). Of course feel free to correct me :)

**Comment by harrism** [comment]
I think it's worth at least exploring why the ordering is different and whether it's a simple cause and fix or if it is something fundamentally different in pygdf.

**Comment by harrism** [comment]
It is not resolved. I get the same output with 0.4.0:

```
import cudf
import pandas as pd

gdf1 = cudf.DataFrame()
gdf2 = cudf.DataFrame()
gdf1['id'] = [10, 11]
gdf1['timestamp'] = [1,2]
gdf1['a'] = [3, 4]

gdf2['id'] = [4,5]
gdf2['a'] = [7, 8]

gdf = gdf1.merge(gdf2, how='left', on=['id', 'a'], type='hash')
print(gdf)

df1 = pd.DataFrame()
df2 = pd.DataFrame()
df1['id'] = [10, 11]
df1['timestamp'] = [1,2]
df1['a'] = [3, 4]

df2['id'] = [4,5]
df2['a'] = [7, 8]

df = df1.merge(df2, how='left', on=['id', 'a'])
print(df)
```

Output:

```
1:int64
2:int64
2:int64
    id    a timestamp
0   10    3         1
1   11    4         2
   id  timestamp  a
0  10          1  3
1  11          2  4
```

**Comment by pearu** [comment]
The ordering of cudf merge is determined by the order of adding columns to cudf Dataframe (its `_cols` attribute is OrderedDict). The ordering of pandas merge is as it is.
To ensure the same ordering, the above PR #678 computes pandas merge on a dummy data
and initializes the cudf Dataframe `_cols` attribute to set the pandas ordering.
